### ISSUE TITLE
SCRIPT_BEFORE and SCRIPT_AFTER don't seem to respect REMOTE_PORT

### ISSUE THREAD

**Issue by npiasecki** [easingthemes/ssh-deploy#104]
For example:

        - name: Deploy worker
          uses: easingthemes/ssh-deploy@v4.0.4
          with:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            REMOTE_HOST: deploy.example.com
            REMOTE_USER: deployuser
            REMOTE_PORT: 14187
            SOURCE: awesome-sauce/publish
            TARGET: /srv/awesome-sauce/app
            SCRIPT_BEFORE: sudo /bin/systemctl stop awesomeapp
            SCRIPT_AFTER: sudo /bin/systemctl start awesomeapp

If I delete SCRIPT_BEFORE and SCRIPT_AFTER, then the rsync operation works on port 14187. But the before and after scripts always seem to be on port 22:

            ssh: connect to host deploy.example.com port 22: Connection timed out

I would intuit that REMOTE_PORT should apply in all cases.

(Thank you for providing this GitHub Action. Throwing a thing out on the Internet and then supporting it for everyone is usually a thankless task.)

**Comment by easingthemes** [comment]
Thanks for the PR.
Published in v4.0.5 https://github.com/easingthemes/ssh-deploy/releases/tag/v4.0.5
