### ISSUE TITLE
Capture rsync output to display in Action Summary / PR Comments

### ISSUE THREAD

**Issue by juanramollino** [easingthemes/ssh-deploy#108]
Idea for enhancement: 

I haven't found a way to capture the value of `$RSYNC_OUTPUT` beyond the context of the command. I want to display the rsync output when a PR is opened; I run it using the `--dry-run` option to understand which files are going to be synchronized, so [me thinks] it could be a good idea to be able to expose the result to the greater GitHub env.

**Comment by easingthemes** [comment]
Example https://github.com/easingthemes/ssh-deploy/blob/main/README.md#usage

**Comment by juanramollino** [comment]
Thanks. It seems this is a no-issue. Haven't had the time to make it work, but I trust this 😄

**Comment by tmugford** [comment]
> Thanks. It seems this is a no-issue. Haven't had the time to make it work, but I trust this 😄

Hey @juanramollino. Did you ever work out how to do this? I’m also trying to pass `$RSYNC_STDOUT` to a subsequent action (Slack), but I can’t work out how. All the examples I’ve seen for capturing the output from an action use `run` in conjunction with `$GITHUB_ENV`, but I can’t see how to do that with this action.

**Comment by juanramollino** [comment]
> > Thanks. It seems this is a no-issue. Haven't had the time to make it work, but I trust this 😄
> 
> Hey @juanramollino. Did you ever work out how to do this? I’m also trying to pass `$RSYNC_STDOUT` to a subsequent action (Slack), but I can’t work out how. All the examples I’ve seen for capturing the output from an action use `run` in conjunction with `$GITHUB_ENV`, but I can’t see how to do that with this action.

Sadly, not. I had to move on to other things, and no one else (but me) complains about the lack of good report in GitHub 😛
