### ISSUE TITLE
SSH key scan does not respect REMOTE_PORT

### ISSUE THREAD

**Issue by XericZephyr** [easingthemes/ssh-deploy#111]
Code: https://github.com/easingthemes/ssh-deploy/blob/ec9347f8c60811cb02d14f028b78f188c3dc18ca/src/sshKey.js#L30

If the port is not default, the ssh-keyscan will fail.

looks like we should do `ssh-keyscan -p ${(remotePort || 22)} -H ${host}  >> ${knownHostsPath}` instead.

**Comment by sebastianblesgen** [comment]
Same issue for me

**Comment by easingthemes** [comment]
Thanks, linked PR merged and change is published in latest v4.1.0
