### ISSUE TITLE
`error in libcrypto`

### ISSUE THREAD

**Issue by selfagency** [easingthemes/ssh-deploy#112]
```
Warning: Permanently added '***' (ED25519) to the list of known hosts.
Load key "/home/runner/.ssh/deploy_key_***_1675266422153": error in libcrypto
***@***: Permission denied (publickey).
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.3]
```

**Comment by joepio** [comment]
I'm having the same issue. 

However, I've also tried using `easingthemes/ssh-deploy@v3`, and [_still_ had the same error](https://github.com/atomicdata-dev/atomic-data-rust/actions/runs/4078098449/jobs/7027900761#step:7:67), so I guess it's not because of a very recent change in this repo.

**Comment by selfagency** [comment]
@joepio yeah, i switched from using `ubuntu-latest` to `ubuntu-20.04` and that seemed to do it.

**Comment by furacas** [comment]
@selfagency i have the same error, I refer to the readme to solve it

> The keys should be generated using the PEM format. You can use this command
> ssh-keygen -m PEM -t rsa -b 4096

**Comment by GNUGradyn** [comment]
This appears to be caused by not having a newline after `-----END OPENSSH PRIVATE KEY-----` in the secret. simply recreating the secret and adding a newline at the end seems to fix it

**Comment by easingthemes** [comment]
Thanks @GNUGradyn, I'll try that.

**Comment by easingthemes** [comment]
I've added new line in a key file.
Let me know if this helped.
Released in v4.1.1, or use @main

**Comment by MrCoder** [comment]
PEM works fine. But when I use ED25519, I have to manually add trailing newline. Otherwise it reports `***@***: Permission denied (publickey).` error.

**Comment by guotingchao** [comment]
I found this issue for same problem, And I solved the problem.

Tips: if u use ssh ED25519,Remember to add a new line after your Private key
