### ISSUE TITLE
Script fails to run but action succeeds

### ISSUE THREAD

**Issue by furacas** [easingthemes/ssh-deploy#115]
I have some scripts that may fail to run, but the Action always succeeds whether it fails or not, I can't get the message that the Action's run failed

**Comment by gigsta12** [comment]
@furacas Are you providing the full path to the script you are wanting to run? Alternatively you could also `cd` to the directory within the `SCRIPT_AFTER` and then call the script.

**Comment by furacas** [comment]
> @furacas Are you providing the full path to the script you are wanting to run? Alternatively you could also `cd` to the directory within the `SCRIPT_AFTER` and then call the script.

sure, What I want to express is that the script fails to run, but the Github Action runs successfully. I expect that when the script fails to run, Github Action prompts failure

**Comment by easingthemes** [comment]
Currently main action task is rsync deployment.
SSH scripts before/after are only logging results or error.
I can add additional param / env var to control this behaviour.
Default will still be just logging.

**Comment by domstubbs** [comment]
That would be really handy – we’re running migrations and reloading services in our post-deploy script, so any failures there are serious and we need to know about them. The individual action logs aren’t likely to be reviewed if they’re being logged as successful.

Thanks for the action, it’s a real timesaver.

**Comment by durch** [comment]
Tacking on to this, we're seeing succesful taks even when `rsync` fails, logs below:

```
❌ [Rsync] error: 
Error: rsync exited with code 23
    at ChildProcess.<anonymous> (/home/runner/work/_actions/easingthemes/ssh-deploy/main/dist/index.js:2:2603)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  code: 23
}
❌ [Rsync] stderr: 
rsync: [generator] recv_generator: mkdir "<dir-name>" failed: Permission denied (13)
*** Skipping any contents from this failed directory ***
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
```

**Comment by vicenterzl** [comment]
+1

**Comment by liushuai05** [comment]
+1

**Comment by weblink-hr** [comment]
+1

**Comment by Koswu** [comment]
Seems This project is supported this feature with this [MR](https://github.com/easingthemes/ssh-deploy/pull/141).

Just use `easingthemes/ssh-deploy@main` and pass  `SCRIPT_AFTER_REQUIRED = true ` variable to it.

Maybe we should mention it in the README.md

**Comment by easingthemes** [comment]
Readme updated: https://github.com/easingthemes/ssh-deploy/blob/main/README.md#12-script_after_required-optional-default-false
```
SCRIPT_AFTER_REQUIRED: true
```
