### ISSUE TITLE
When TARGET is unset, it doesn't default to /home/username

### ISSUE THREAD

**Issue by sturmery** [easingthemes/ssh-deploy#117]
https://github.com/easingthemes/ssh-deploy/blob/85987f45673377acac05c68558e18e5d4d0bcfec/src/inputs.js#L14

Somehow if TARGET is not set, it'll try to rsync into `/home/REMOTE_USER`, looks like that L14 fails to obtain the proper value.  Tested this on all versions of this action.  Once I've set `TARGET: /home/${{ secrets.AWS_EC2_SSH_USERNAME }}` in my YAML file, everything worked.

**Comment by easingthemes** [comment]
Fixed in v4.1.1.
