### ISSUE TITLE
Is your Shell Clean Error.

### ISSUE THREAD

**Issue by epixelsoft** [easingthemes/ssh-deploy#128]
Please help with following error - 

❌ [Rsync] stderr: 
Warning: Permanently added '***' (ED25519) to the list of known hosts.
protocol version mismatch -- is your shell clean?
(see the rsync manpage for an explanation)
rsync error: protocol incompatibility (code 2) at compat.c([62](https://github.com/epixelsoft/chatoo_festa/actions/runs/4480323035/jobs/7878233477#step:3:63)2) [sender=3.2.7]

❌️ [Rsync] stdout: 

❌ [Rsync] command: 
================================================================
================================================================
Error: R] rsync exited with code 2

Warning: Permanently added '***' (ED25519) to the list of known hosts.
protocol version mismatch -- is your shell clean?
(see the rsync manpage for an explanation)
rsync error: protocol incompatibility (code 2) at compat.c(622) [sender=3.2.7]

**Comment by lnfel** [comment]
You should check the relevant error on rsync manpage, it should point you to fixing the issue.

**Comment by epixelsoft** [comment]
Thank you for responding to this one. I have seen the man page and followed the troubleshoot, still issue is same. I have updated rsync version as same as github has. 

https://linux.die.net/man/1/rsync

**Comment by thehive-enterprise** [comment]
I am facing same issue while deploying to EC2 instance. Any fix?
