### ISSUE TITLE
MS VS code editor error

### ISSUE THREAD

**Issue by altrusl** [easingthemes/ssh-deploy#129]
MS VS code with `GitHub Actions` extension gives an error for this action:

**Missing required inputs: `SSH_PRIVATE_KEY`, `REMOTE_HOST`, `REMOTE_USER`**

<img width="380" alt="error-screenshot" src="https://user-images.githubusercontent.com/29726515/227782054-472d76f9-d3fe-4155-98a2-076b40845589.png">

No errors if i replace `env` with `with`

**Comment by bensandee** [comment]
I see this too. In https://github.com/easingthemes/ssh-deploy/blob/main/src/inputs.js
```javascript  
const inputVal = process.env[input] || process.env[`INPUT_${input}`] || defaultInputs[inputName];
```
I wonder if the INPUT environment variable should be prioritized over the general env variable, like this:
```javascript  
const inputVal = process.env[`INPUT_${input}`] || process.env[input] || defaultInputs[inputName];
```
It could be that your environment has some of those values defined already and they are taking priority.
