### ISSUE TITLE
More than one REMOTE_HOST

### ISSUE THREAD

**Issue by churnd** [easingthemes/ssh-deploy#13]
Is it possible to use more than one REMOTE_HOST variable, for when we would have more than one host we want to deploy to?

**Comment by easingthemes** [comment]
Hey @churnd, you can add multiple steps with same action:
`    - name: Deploy to Staging
      uses: easingthemes/ssh-deploy@v2.1.4
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE: "dist/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
    - name: Deploy to Prod
      uses: easingthemes/ssh-deploy@v2.1.4
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE: "dist/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}`

**Comment by easingthemes** [comment]
https://github.com/easingthemes/ssh-deploy/issues/20
