### ISSUE TITLE
Env variables in the SCRIPT_BEFORE and SCRIPT_AFTER scripts

### ISSUE THREAD

**Issue by altrusl** [easingthemes/ssh-deploy#130]
Hello

Thank you for the good software

Is there any way to use env variables (from `jobs->deploy->env` section) in the scripts?

I have to surround your action with `appleboy/ssh-action@master` to use them

**Comment by mrl22** [comment]
I have this same issue. I am trying to build a similar feature to Capistrano but I am unable to use ${GITHUB_SHA::6}

```
SCRIPT_AFTER: |
            cd ./releases/
            pwd
            ls -t | awk 'NR>5' | xargs -L1 rm -rf # Keep only the latest 5 commits for rolling back
            cd ${GITHUB_SHA::6}
            pwd
            mkdir ../../storage
            ln -s storage ../../storage
            php artisan storage:link
            pwd
            ln -s ./ ../../public_html 
            echo $RSYNC_STDOUT
```

@altrusl do you have an example of how you are doing it with ssh-action?

**Comment by davidavz** [comment]
Any news ?

**Comment by hokoo** [comment]
The same issue
