### ISSUE TITLE
Two deploy， SCRIPT_BEFORE will be confusion

### ISSUE THREAD

**Issue by kc-cfw** [easingthemes/ssh-deploy#131]
When I make two deployments, the temporary file generated by this **SCRIPT_BEFORE**
`local_ssh_script-before.sh`, the second one will continue to use the content of the previous one because of `Required file exist`, causing confusion

**Comment by easingthemes** [comment]
Fixed in the latest version v4.1.9 - https://github.com/easingthemes/ssh-deploy/pull/167/files#diff-9b163fdf32814f608c5eb67fb0841aa3dfa17545829fbbea2fe053b5991796e6R16.

**Comment by codespearhead** [comment]
@kc-cfw Can you check whether the problem is still reproducible in v4.1.9? If it isn't, do you mind closing this issue?
