### ISSUE TITLE
Set ssh cmd params fail

### ISSUE THREAD

**Issue by csrftoken** [easingthemes/ssh-deploy#146]
Config
![image](https://github.com/easingthemes/ssh-deploy/assets/29940756/80428ec6-c881-4a0f-8f87-4bd3e70e7f9e)

But got
![image](https://github.com/easingthemes/ssh-deploy/assets/29940756/48b72f27-4b6b-4238-9d46-19b4a9629bc9)

Please take a look, thanks ~

**Comment by Hermanverschooten** [comment]
It looks to me that the SSH_CMD_ARGS are not being used in the ssh call for the scripts, only for the ssh connection in the rsync.
