### ISSUE TITLE
Support GH Action Highlight

### ISSUE THREAD

**Issue by Triloworld** [easingthemes/ssh-deploy#149]
Plugin take overhead from this repo when comes to writing Github Action
Issue is when we try go along with readme

Plugin in VS Code:
https://github.com/github/vscode-github-actions

This give error:
<img width="712" alt="Zrzut ekranu 2023-05-16 o 13 01 01" src="https://github.com/easingthemes/ssh-deploy/assets/2671726/fe4a6b27-1618-4ed3-8873-bf8a1f5ef8b8">

This will be ok:
<img width="596" alt="Zrzut ekranu 2023-05-16 o 13 04 22" src="https://github.com/easingthemes/ssh-deploy/assets/2671726/f4f1650f-4562-4f22-a42c-c9a685ab847c">

Maybe fix readme? What is proper approach?

**Comment by AlexDroomer** [comment]
Hi, @Triloworld , you can leave the options only in the `with` block and remove the `env` block, everything will work as it should, the README does not really specify this, but in the file action.yml is written not required/required variables

**Comment by Triloworld** [comment]
GitHub Action documentation: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepswith
You are right. This file describe it as INPUT: https://github.com/easingthemes/ssh-deploy/blob/main/action.yml
You can merge change into readme if that's ok for you and close issue. For me it will align with other tools that are strict regarding checking syntax.
Thank you for this action :) Work great overall.

**Comment by Triloworld** [comment]
@AlexDroomer is there issue to merge pull request?

**Comment by AlexDroomer** [comment]
@Triloworld I don't know, I don't have permission to merge🤖

**Comment by Triloworld** [comment]
@sdelfi and @easingthemes

**Comment by easingthemes** [comment]
Merged, thanks.
