### ISSUE TITLE
Update to Node 20

### ISSUE THREAD

**Issue by Pesa** [easingthemes/ssh-deploy#166]
Please update the action to use Node 20. Node 16 is EOL. See https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by codespearhead** [comment]
Correction: as of today, [Node 18.x is the latest version of Node](https://nodejs.org/en).

**Comment by codespearhead** [comment]
As of today, [Node 18.x is the latest LTS version of Node](https://nodejs.org/en).

@Pesa Are you willing to make a PR?

**Comment by Pesa** [comment]
> As of today, [Node 18.x is the latest LTS version of Node](https://nodejs.org/en).

Right. Github's post specifically mentions Node 20 though, which is set to become the active LTS in about a month. My guess is that Github prefer skipping one LTS so that they can do one migration every two years instead of every year. IIRC they did the same with the transition from Node 12 to 16.

> @Pesa Are you willing to make a PR?

Unfortunately I know nothing about Javascript or Node :(

**Comment by Pesa** [comment]
This is still relevant. Please reopen.
