### ISSUE TITLE
Multiple SH Files are showing on  server

### ISSUE THREAD

**Issue by webbyus** [easingthemes/ssh-deploy#172]
@easingthemes @sebastianblesgen   I added `SCRIPT_BEFORE: |` , `SCRIPT_AFTER` to my YAML file,I can see multiple temp .`sh` files are in there  . How could I clear those things ?  

<a target="_blank" href="https://imageupload.io/MuUeH9od1f0CAZG"><img  src="https://imageupload.io/ib/bDimeyYcwgRXDF4_1696730900.png" alt="temp.png"/></a>

**Comment by easingthemes** [comment]
This was introduced in latest release to fix https://github.com/easingthemes/ssh-deploy/issues/164 - enabling usage of the action multiple times.
Now we need update to remove temp files once script is executed.

**Comment by nickfera** [comment]
I am using ubuntu and added a command to `SCRIPT_AFTER` to find files that match the name and delete them. Note that in `SCRIPT_BEFORE` I navigate to the folder where the files are located before running this line.

`find ./ -name "local_ssh_script-before*" | xargs rm`

Run the command without `| xargs rm` through the terminal just to be sure that it's in the correct directory and finding the files.
