### ISSUE TITLE
Missing declarations for SCRIPT_BEFORE_REQUIRED and SCRIPT_AFTER_REQUIRED flags

### ISSUE THREAD

**Issue by skyArony** [easingthemes/ssh-deploy#177]
The commits added by the #141  work as expected, but there is a lack of relevant declarations in `action.yml`, leading to:

1. VS Code prompting `Invalid action input 'SCRIPT_BEFORE_REQUIRED'` and `Invalid action input 'SCRIPT_AFTER_REQUIRED'`
2. GitHub Action execution displaying a warning: `"Unexpected input(s) 'SCRIPT_BEFORE_REQUIRED', 'SCRIPT_AFTER_REQUIRED', valid inputs are ['SSH_PRIVATE_KEY', 'REMOTE_HOST', 'REMOTE_USER', 'REMOTE_PORT', 'SOURCE', 'TARGET', 'ARGS', 'SSH_CMD_ARGS', 'EXCLUDE', 'SCRIPT_BEFORE', 'SCRIPT_AFTER']".`

Therefore, I have added the relevant declarations in the PR to fix this issue.

**Comment by dgw** [comment]
Shouldn't this be closed as completed after #178 was merged + a release went out with the fix?

**Comment by skyArony** [comment]
release at v5.0.2
