### ISSUE TITLE
Unable to resolve action `easingthemes/ssh-deploy@v5`, unable to find version `v5`

### ISSUE THREAD

**Issue by alekw** [easingthemes/ssh-deploy#179]
Hello, I tried to update my workflow from:

```
    - name: Deploy to Production server
      uses: easingthemes/ssh-deploy@v4
```
to
```
    - name: Deploy to Production server
      uses: easingthemes/ssh-deploy@v5
```
and my action failed with: Unable to resolve action `easingthemes/ssh-deploy@v5`, unable to find version `v5`

I don't have much knowledge about publishing actions, but I think this is caused by v5 branch is not created in git.

**Comment by wilianmaique** [comment]
- name: deploy
      uses: easingthemes/ssh-deploy@main

**Comment by easingthemes** [comment]
Latest version is v5.0.0

```
              - name: ssh deploy
                uses: easingthemes/ssh-deploy@v5.0.0
```

**Comment by easingthemes** [comment]
Some actions are publishing  `v5` as an alias to latest `v5.x.x`, but this requires a lot of maintenance. If there is some automated way to do this I would add it, but for now, short versions are not supported.
