### ISSUE TITLE
Reporting Security Vulnerability

### ISSUE THREAD

**Issue by dwisiswant0** [easingthemes/ssh-deploy#182]
Hi @easingthemes,

As there is currently no [`SECURITY.md`](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) policy in place, could you please [activate private vulnerability reporting](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository#enabling-or-disabling-private-vulnerability-reporting-for-a-repository) for this repo to facilitate coordinated vulnerability disclosure?

Thank you.

**Comment by Pesa** [comment]
@dwisiswant0 vulnerability reporting seems to be already enabled, see here: https://github.com/easingthemes/ssh-deploy/security/advisories/new

**Comment by dwisiswant0** [comment]
Thanks, @Pesa!
