### ISSUE TITLE
property source can support muti-folder?

### ISSUE THREAD

**Issue by ibwei** [easingthemes/ssh-deploy#21]
`   
env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
`
I want upload the .nuxt & static & package.json & nuxt.config.js folder or file which is in the root path,so how can i do it?

**Comment by 4lessandrodev** [comment]
Have you tried to create a folder in the environment before deploy?

`
- name: Create application folder
  run: mkdir application && cp -r dist application/dist && cp -r package.json application/
`

**Comment by hkmaly** [comment]
Doesn't change the fact that ability to copy multiple things would be neat.

**Comment by easingthemes** [comment]
Added support for multiple sources, same as `rsync` native:
Path to src. Can be a single filename, or an array of filenames. Shell wildcard expansion is supported. Examples:
```
src: "./dist/"
src: ["./dir-a/file1","./dir-b/file2"]
src: "./*.foo"
src: "foo{1,2,3}.txt"
etc.
```
