### ISSUE TITLE
SOURCE not really optional

### ISSUE THREAD

**Issue by basith374** [easingthemes/ssh-deploy#22]
Hi, I have left out `SOURCE` and the rsync command fails during deployment

```
[Rsync] Starting Rsync Action: /home/runner/work/my-app/my-app/undefined 
rsync: link_stat "/home/runner/work/my-app/my-app/undefined" failed: No such file or directory (2)
⚠️ [Rsync] cmd:  rsync /home/runner/work/my-app/my-app/undefined
```

I had to set `SOURCE: ''` to fix it

**Comment by easingthemes** [comment]
Hey @basith374, thanks for reporting. This was fixed in previous bugfix release https://github.com/easingthemes/ssh-deploy/commit/14eb503e6256d31b478a8f11cd538d759b97bf59#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R65

Can you please try with latest release v2.1.5
