### ISSUE TITLE
iprange to whitelist

### ISSUE THREAD

**Issue by gitdckap** [easingthemes/ssh-deploy#24]
what is your iprange to whitelist for ssh.
we would like to whitelist in our server, then we will configure

**Comment by easingthemes** [comment]
Hi @gitdckap, this is just Github action, so it's run on Github machines. So you need to follow their updates for IP adresses. Currently: https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#ip-addresses

**Comment by gitdckap** [comment]
sorry brother it is not working,
I hope you have sent the IP for GitHub hosted runner.
I will not work for ssh-deploy with GitHub action.

**Comment by easingthemes** [comment]
Sorry, I don't understand what's the issue, can you add more info. Thanks
