### ISSUE TITLE
Deployment Failed; Unauthorized

### ISSUE THREAD

**Issue by oProtica** [easingthemes/ssh-deploy#31]
I am getting an issue with deployment due to being unauthorized on the vps I am deploying to, I created a private / public key pair on my local machine and copied the public key to my the `authorized_keys` file on the vps I am deploying to which is running debian, I am also running debian on my local machine. I stored the private key as a secret in github. On push, all steps work correctly except deployment and it returns unauthorized. I believe it is because I have not supplied the key password which I am not sure how to do.

**Comment by joepio** [comment]
I think I'm having a similar issue, this is the log from [the action](https://github.com/joepio/atomic-data-rust/runs/3339727632?check_suite_focus=true):

```
✅ [SSH] file created.
✅ Ssh key added to `.ssh` dir  /home/runner/.ssh/deploy_key
[Rsync] Starting Rsync Action: /home/runner/work/atomic-data-rust/atomic-data-rust/README.md to ***@***:~/atomic-server/master-
[Rsync] exluding folders 
⚠️ [Rsync] error:  rsync exited with code 255
⚠️ [Rsync] stderr:  Warning: Permanently added '***' (ECDSA) to the list of known hosts.
Permission denied, please try again.
Permission denied, please try again.
***@***: Permission denied (publickey,password).
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(235) [sender=3.1.3]

⚠️ [Rsync] stdout:  
⚠️ [Rsync] cmd:  rsync /home/runner/work/atomic-data-rust/atomic-data-rust/README.md ***@***:~/atomic-server/master- --rsh "ssh -p 22 -i /home/runner/.ssh/deploy_key -o StrictHostKeyChecking=no" --recursive --exclude= -rltgoDzvO
```

- I've created an SSH key using `ssh-keygen -t rsa -b 4096`, without setting a passphrase
- I've copied the PEM private key to a Github Secret and passed it in the [`deployment.yml` workflow](https://github.com/joepio/atomic-data-rust/blob/3d83e8ba64a9f5cfd851c302af87530bf1e44936/.github/workflows/deployment.yml#L1).                                                                                       
- I've appended the public key to the server side `~/.ssh/known_hosts` file
- I've checked that the user (`root`) has the correct rights to write at the target - he has.
