### ISSUE TITLE
I

### ISSUE THREAD

**Issue by digitlimit** [easingthemes/ssh-deploy#34]
Please what am I missing? I'm getting the error below:

```
[general] GITHUB_WORKSPACE:  /home/runner/work/wordpress/wordpress
[SSH] /home/runner/.ssh dir exist
[SSH] /home/runner/.ssh/known_hosts file exist
✅ Ssh key added to `.ssh` dir  /home/runner/.ssh/deploy_key
[Rsync] Starting Rsync Action: /home/runner/work/wordpress/wordpress/dist/ to ***@***:/home/REMOTE_USER/
⚠️ [Rsync] error:  rsync exited with code 255
⚠️ [Rsync] stderr:  Load key "/home/runner/.ssh/deploy_key": invalid format
Permission denied, please try again.
Permission denied, please try again.
***@***: Permission denied (publickey,password).
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(235) [sender=3.1.3]

```

**Comment by GreatAuk** [comment]
same issue

**Comment by GreatAuk** [comment]
@digitlimit 
doc
![image](https://user-images.githubusercontent.com/20253809/112135401-b1782480-8c08-11eb-9d51-2a76aa878798.png)

**Comment by sebastienserre** [comment]
Hello,
I have the same issue.
I've created a key with `ssh-keygen -m PEM -t rsa -b 4096` on my Ubuntu 20.04. Added it to Github Secrets and to /home/myhome/.ssh/authorized_key on my server...
What do I miss ?

**Comment by sebastienserre** [comment]
I know What I missed !
"Private key part of an SSH key pair." I missed the "Private" ;-)

**Comment by workkk98** [comment]
> I know What I missed !
> "Private key part of an SSH key pair." I missed the "Private" ;-)

How to solve this problem？

**Comment by workkk98** [comment]
> > I know What I missed !
> > "Private key part of an SSH key pair." I missed the "Private" ;-)
> 
> How to solve this problem？

I find the reason.If private key is in id_rsa file,  I should copy all content assign to `SERVER_SSH_KEY `，include `---private key start----`.

**Comment by miracletjf** [comment]
The private key needs to be converted to PEM format.
Use `ssh-keygen -p -f ~/.ssh/id_rsa -m pem`

**Comment by dridihaythem** [comment]
thank you @miracletjf  :)

**Comment by jrmeurer** [comment]
Finally got it working! My problem was that my SSH Key was password protected. Had to recreate it without a password.

**Comment by iamunadike** [comment]
I think this guys package is a SCAM please beware you end up using PRIVATE Key into your server which means it can be hacked.
Also did you READ the DISCLAIMER, if someoone hacks into your AWS thats it 
I dont Trust this easingprocess smh

**Comment by iamunadike** [comment]
Disclaimer is at the bottom of the index page
too much credentials has been given which should not have

**Comment by DamienDaco** [comment]
> 

I'm not sure if you're trolling or not, but using a private SSH key to authenticate with a remote server is mandatory at some point.
No private SSH key, no login.

**Comment by zhanfenghai** [comment]
> @digitlimit doc ![image](https://user-images.githubusercontent.com/20253809/112135401-b1782480-8c08-11eb-9d51-2a76aa878798.png)

I have do it follow the steps ,but also get the problem.

**Comment by zhanfenghai** [comment]
> Please what am I missing? I'm getting the error below:
> 
> ```
> [general] GITHUB_WORKSPACE:  /home/runner/work/wordpress/wordpress
> [SSH] /home/runner/.ssh dir exist
> [SSH] /home/runner/.ssh/known_hosts file exist
> ✅ Ssh key added to `.ssh` dir  /home/runner/.ssh/deploy_key
> [Rsync] Starting Rsync Action: /home/runner/work/wordpress/wordpress/dist/ to ***@***:/home/REMOTE_USER/
> ⚠️ [Rsync] error:  rsync exited with code 255
> ⚠️ [Rsync] stderr:  Load key "/home/runner/.ssh/deploy_key": invalid format
> Permission denied, please try again.
> Permission denied, please try again.
> ***@***: Permission denied (publickey,password).
> rsync: connection unexpectedly closed (0 bytes received so far) [sender]
> rsync error: unexplained error (code 255) at io.c(235) [sender=3.1.3]
> ```

Did you slove the issue

**Comment by zhanfenghai** [comment]
> 

it does not work
