### ISSUE TITLE
bash: rsync: command not found

### ISSUE THREAD

**Issue by jw-star** [easingthemes/ssh-deploy#38]
⚠️ [Rsync] error:  rsync exited with code 12
⚠️ [Rsync] stderr:  Warning: Permanently added '***' (ECDSA) to the list of known hosts.
bash: rsync: command not found
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(235) [sender=3.1.3]

**Comment by jw-star** [comment]
最新的虚拟环境 有问题切换版本就好了

jobs:
  deploy:
    runs-on: ubuntu-18.04

**Comment by jw-star** [comment]
远程服务器安装即可  apt-get install rsync

**Comment by easingthemes** [comment]
I've updated action to install `rsync` if it's missing.

For now it's using `apt-get install rsync`.
For other OS you need to install `rsync` on the host manually.
