### ISSUE TITLE
Excludes ignored

### ISSUE THREAD

**Issue by apsg** [easingthemes/ssh-deploy#39]
I have following configuration:
![image](https://user-images.githubusercontent.com/3952574/114013638-07370880-9868-11eb-9c47-1493cf107f82.png)

and despite having `node_modules` in excludes, it still copies it over to server. How can I disable it?

**Comment by easingthemes** [comment]
EXCLUDE option was added in v2.1.6 https://github.com/easingthemes/ssh-deploy/releases/tag/v2.1.6

**Comment by apsg** [comment]
Oh, I see. Then it should be corrected in readme:
![image](https://user-images.githubusercontent.com/3952574/114049924-23e53780-988c-11eb-9e39-c031d832bb15.png)

**Comment by easingthemes** [comment]
It's hard to keep readme updated with small version updates, so for now it's just an info:
```!!! Please use latest version, Readme file is just an example, eg: ssh-deploy@v2.1.5```

**Comment by zacker330** [comment]
Can it exclude a specific file only? All docs are about folders.
