### ISSUE TITLE
Keeping version up to date

### ISSUE THREAD

**Issue by oneEyedSunday** [easingthemes/ssh-deploy#41]
Hello there, great tool.

Is there a way to publish a "latest" tag when you deploy to the market place? That way one can always use the latest version.

The README also lags behind a bit, currently pointing to v2.1.15 as against v2.1.16

**Comment by easingthemes** [comment]
Thanks. Definitely annoying to maintain it manually. I've just checked https://docs.github.com/en/actions/creating-actions/about-actions#using-tags-for-release-management, and looks like I can use one release and multiple tags to keep it simple to use latest version
```
uses: easingthemes/ssh-deploy@v2
```
I'll try this approach.

**Comment by oneEyedSunday** [comment]
Great

**Comment by easingthemes** [comment]
In order o use latest version, use
```
uses: easingthemes/ssh-deploy@main
```
