### ISSUE TITLE
GIT submodule & .git folder

### ISSUE THREAD

**Issue by velykanov** [easingthemes/ssh-deploy#44]
Good day everyone!

I'd like to mention two things here and would like to request fixing them (at least the one with `.git` folder):

1. When I'm specifying `.git/` folder to be excluded while deployment it still appears on the server (I've tried `EXCLUDE: ".git/"` and `EXCLUDE: "/.git/"` - both options end up with the same result).
2. I've got submodule in my project and after deployment folder appears to be empty at all. However in fact it points to another git folder which also must be deployed.

**Comment by golee** [comment]
Update module version to 2.1.6 works for me. The verison on Readme doesn't updated yet
```yaml
uses: easingthemes/ssh-deploy@v2.1.6
````

**Comment by velykanov** [comment]
Hey @golee 
I'll try that, thanks!

**Comment by nahuelcandia** [comment]
Still doesn't work :(

**Comment by easingthemes** [comment]
This should be fixed.
