### ISSUE TITLE
Ability to add ssh option

### ISSUE THREAD

**Issue by craxrev** [easingthemes/ssh-deploy#64]
Hi,

So I've been trying to find a way to add an ssh option (-o) to the rsync cmd args, is there a way that I don't know about or is not documented yet?

My goal is to add this ssh option: `-o KexAlgorithms=ecdh-sha2-nistp521` in order to fix a bug with rsync when connecting to the ssh host, I can see that the rsync is using by default, this cmd line option `--rsh "ssh -p 22 -i /runner/.ssh/deploy_key -o StrictHostKeyChecking=no"`..

I would appreciate any guiding on that, thanks in advance

**Comment by easingthemes** [comment]
Option added:
```
11. SSH_CMD_ARGS (optional, default '-o StrictHostKeyChecking=no')
A list of ssh arguments, they must be prefixed with -o and separated by a comma, for example: -o SomeArgument=no, -o SomeOtherArgument=5
```
