### ISSUE TITLE
Post-deployment commands

### ISSUE THREAD

**Issue by thallesdaniell** [easingthemes/ssh-deploy#66]
In some projects, it is necessary to run commands after deployment. I'm creating another step just to run the post-deployment steps. But it would be nice to have the deployment and execution in just one step.

**Comment by seedsaad** [comment]
use this one: appleboy/ssh-action@master

**Comment by easingthemes** [comment]
Feature added:


9. SCRIPT_BEFORE (optional, default '')
Script to run on host machine before rsync. Single line or multiline commands. Execution is preformed by storing commands in .sh file and executing it via .bash over ssh

10. SCRIPT_AFTER (optional, default '')
Script to run on host machine after rsync. Rsync output is stored in $RSYNC_STDOUT env variable.

<img width="820" alt="Screenshot 2023-01-03 at 04 12 32" src="https://user-images.githubusercontent.com/2750284/210295864-36dbadea-8007-4887-a844-e58b5d34d6b5.png">
