### ISSUE TITLE
Consistent naming of SSH_PRIVATE_KEY and SERVER_SSH_KEY in README.md

### ISSUE THREAD

**Issue by joepio** [easingthemes/ssh-deploy#67]
`SSH_PRIVATE_KEY` and `SERVER_SSH_KEY` are both used in the README, which led me to use the wrong name in my Github Secrets. Not a very big issue, but if the readme is updated you might save next users a couple of failed runs

**Comment by Reallisticus** [comment]
Great comment, spared me hours of rigorous debugging :D

**Comment by easingthemes** [comment]
Thanks,
fixed
