### ISSUE TITLE
Feature request: option to run mkdir -p before sync

### ISSUE THREAD

**Issue by reinder** [easingthemes/ssh-deploy#69]
I use ssh-deploy for a while now, it is great! However I've one issue. If the remote directory path not fully exists it fails. In my case the branch name is part of the remote path. Whenever a new branch is create the deployment fails because the branch dir doesn't exist remotely. This can be solved by manually creating the directory, however it would be great if ssh-deply can handle it by running `mkdir -p <path>` over ssh before the sync :)

Console log when the branch dir `interface-controller` doesn't exists:
```
[Rsync] Starting Rsync Action: /home/runner/work/traintastic/traintastic/dist/* to ***@***:***/traintastic/interface-controller/211/
[Rsync] exluding folders 
⚠️ [Rsync] error:  rsync exited with code 11
⚠️ [Rsync] stderr:  Warning: Permanently added '[***]:***,[51.195.100.163]:***' (ECDSA) to the list of known hosts.
rsync: mkdir "***/traintastic/interface-controller/211" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(682) [Receiver=3.1.3]
```

**Comment by lrineau** [comment]
The [rsync option `--mkpath`](https://download.samba.org/pub/rsync/rsync.1#opt--mkpath) is made for that reason:
> Create all missing path components of the destination path.

Click on the link for the full documentation of the option.

**Comment by easingthemes** [comment]
Feature added:

9. SCRIPT_BEFORE (optional, default '')
Script to run on host machine before rsync. Single line or multiline commands. Execution is preformed by storing commands in .sh file and executing it via .bash over ssh

10. SCRIPT_AFTER (optional, default '')
Script to run on host machine after rsync. Rsync output is stored in $RSYNC_STDOUT env variable.

<img width="820" alt="Screenshot 2023-01-03 at 04 12 32" src="https://user-images.githubusercontent.com/2750284/210296028-313a9340-fb37-4ce4-868d-a666b720d123.png">
