### ISSUE TITLE
I want to deploy with password, OK?

### ISSUE THREAD

**Issue by bbhxwl** [easingthemes/ssh-deploy#70]
I want to deploy with password, OK?

**Comment by Brugman** [comment]
https://github.com/appleboy/scp-action lets you deploy with an SSH password instead of a key.

**Comment by Peter-JXL** [comment]
Hi, I create a key with password: 
```
$ ssh-keygen
...
Enter passphrase (empty for no passphrase):     # In here I input a password
```
are there an option to config password?  I read readme.md and read some issue, seem that there is no similar issue

**Comment by shoshins** [comment]
@easingthemes  @Peter-JXL I would offer to agree that RSYNC and SSH won't allow putting passwords for private keys into CLI Command. 

Let's just state that in the documentation. I had the same issue.
