### ISSUE TITLE
Rsync: command not found

### ISSUE THREAD

**Issue by xCryzed** [easingthemes/ssh-deploy#72]
Hello guys,

my deployment is also not working anymore. I'm getting the following error:

```
⚠️ [Rsync] error:  rsync exited with code 12
⚠️ [Rsync] stderr:  Warning: Permanently added '[***]:***,[xxx.xx.xxx.xxx]:***' (ECDSA) to the list of known hosts.
bash: line 1: rsync: command not found
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(235) [sender=3.1.3]
``` 

Do you have any ideas?

**Comment by danielroccha** [comment]
@xCryzed how dou solve this ?

**Comment by xCryzed** [comment]
@danielroccha I think the problem was that I updated the debian version and because of that no rsync was installed anymore.

**Comment by jakewhiteley** [comment]
This is still happening

**Comment by ItsYasser** [comment]
Still facing the same issue

**Comment by stockime** [comment]
Had the same issue.

`rsync` has to also be installed on the remote machine.

**Comment by DmitryArkh** [comment]
> `rsync` has to also be installed on the remote machine.
This should be definitely mentioned in the readme
