### ISSUE TITLE
Github action ssh-deploy Security group of Ec2 instance

### ISSUE THREAD

**Issue by amitgupta5888** [easingthemes/ssh-deploy#74]
In order to use **easingthemes
/ssh-deploy**, what IPs should be allowed in EC2 instance security group where we want to deploy code.
Since GitHUB action runner can assume any IP, does it mean that we need to allow SSH on our server from whole internet. is there any workaround for this

**Comment by ericghara** [comment]
I had the same question.  Looks like [GitHub runners use Azure](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#cloud-hosts-for-github-hosted-runners)'s IP address ranges for everything but macOS.

**Comment by easingthemes** [comment]
As shared above:

```
GitHub provides runners that you can use to run your jobs, or you can
...
To get a list of IP address ranges that GitHub Actions uses for GitHub-hosted runners, you can use the GitHub REST API. For more information, see the actions key in the response of the "[Get GitHub meta information](https://docs.github.com/en/rest/reference/meta#get-github-meta-information)" endpoint.
```

It's a quit big list, so depending on your use case, having self hosted runner can make sense. With self hosted runner, you control IP.

<img width="607" alt="Screenshot 2023-01-03 at 04 59 57" src="https://user-images.githubusercontent.com/2750284/210298545-4f6ab4fb-137b-49ee-902c-fdf685ca55d7.png">
