### ISSUE TITLE
Is it possible to deploy incrementally?

### ISSUE THREAD

**Issue by yuanhaozzz** [easingthemes/ssh-deploy#78]
[http://yuanhao-web.cn/server/uploads/20220529112133.jpg](url)
For web multi-page applications, the files in the dist will be deleted before deployment. Can it be directly overwritten? ?

**Comment by easingthemes** [comment]
`rsync` has a lot of options. Depending what you want to achieve, eg https://digitalis.io/blog/linux/incremental-backups-with-rsync-and-hard-links/

<img width="1076" alt="Screenshot 2023-01-03 at 05 06 22" src="https://user-images.githubusercontent.com/2750284/210298911-db5204eb-9727-42a5-aebc-d77f1069bfca.png">

Use **ARGS** env variable
```
5. ARGS (optional, default '-rltgoDzvO')
For any initial/required rsync flags, eg: -avzr --delete
```
