### ISSUE TITLE
Build stays in "Starting Rsync Action" forever

### ISSUE THREAD

**Issue by MyNameIsBatman** [easingthemes/ssh-deploy#8]
I am new to Actions and I really don't know what I am doing wrong. Initially I had a authentication error but then I saw that I needed to provide the private key instead of the public one, ok! But now my build runs forever when reach "[Rsync] Starting Rsync Action:" part and nothing is really copied to my server.

**Comment by JaccovdP** [comment]
Hi, I had the same issue. However, simply running the build again solved the problem for me.

**Comment by easingthemes** [comment]
Error handling and logging updated.
