### ISSUE TITLE
Use Node.js 16

### ISSUE THREAD

**Issue by OneYellowLemon** [easingthemes/ssh-deploy#82]
As per [the recent announcement from GitHub](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/), all Actions will be required to run on Node.js 16 by Summer 2023.

![2022-10-11_05-14-21-PM_176ms](https://user-images.githubusercontent.com/66096725/195199642-0a686cdb-1151-4666-a58e-6b608623d900.png)

**Comment by anuteresa** [comment]
@easingthemes Can you update this workflow to run on node.js16

**Comment by easingthemes** [comment]
Thanks,
Fixed in latest major release v3
