### ISSUE TITLE
Support HostKeyAlgorithms & PubkeyAcceptedKeyTypes

### ISSUE THREAD

**Issue by TheRankin** [easingthemes/ssh-deploy#88]
in SSH we can specify the HostKeyAlgorithms and PubkeyAcceptedKeyTypes to establish the connection

ssh-deploy doesn't have an input to say if is a ssh-rsa or ssh-dss key type

Recently, I get this message:

``
Unable to negotiate with *** port ***: no matching host key type found. Their offer: ssh-rsa,ssh-dss
``

and I found that putting 

``
REMOTE_PORT: ${{ secrets.REMOTE_PORT }} -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa
`` 

fix the problem

**Comment by suhaibkn** [comment]
> `REMOTE_PORT: ${{ secrets.REMOTE_PORT }} -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa`

Thanks a ton. I was also looking for a way to pass `HostKeyAlgorithms` to the underlying `ssh` command.

I'll be using this until #85 gets merged.

**Comment by easingthemes** [comment]
Nice trick :)
With latest updates `SSH_CMD_ARGS` can be used:

11. SSH_CMD_ARGS (optional, default '-o StrictHostKeyChecking=no')
A list of ssh arguments, they must be prefixed with -o and separated by a comma, for example: -o SomeArgument=no, -o SomeOtherArgument=5
