### ISSUE TITLE
More description about SSH_PRIVATE_KEY

### ISSUE THREAD

**Issue by tbntdima** [easingthemes/ssh-deploy#9]
```
SSH_PRIVATE_KEY [required]
This should be the private key part of an ssh key pair. The public key part should be added to the authorized_keys file on the server that receives the deployment.

The keys should be generated using the PEM format. You can use this command

ssh-keygen -m PEM -t rsa -b 4096
```

Hi, I'm a newbie in networking, so it took me a while to figure out what should be done here.

I'll try to explain what I understood, maybe it will be helpful to someone else 🙂 

I run `ssh-keygen -m PEM -t rsa -b 4096` locally, and saved keys into a new folder (not to mess up with existing ones).
Then the private key, I put in GitHub secrets. And the public one I added to my server `.ssh/authorized_keys` file.

Initially, I was trying to generate keys on the server as well 😅. And couldn't understand why it's not working. 

That's it 🙃 I think it's would be too silly to put in readme file, so I did it in the issue.

**Comment by easingthemes** [comment]
Thanks, I've add a link for more info.
