### ISSUE TITLE
"Rsync error:  rsync exited with code 255" since some days ago

### ISSUE THREAD

**Issue by titodevera** [easingthemes/ssh-deploy#91]
Hello!

Since a few days ago the ssh-deploy of my repository has stopped working, without having made any changes.

I have other repositories with similar configurations working fine but this one is driving me crazy...

I have tried regenerating the .ssh keys but I keep getting the same error. From my terminal on Mac I can connect just fine using "ssh -i ~/.ssh/id_rsa user@host.com" with the same private key

![ci](https://user-images.githubusercontent.com/11556124/207294744-11b94627-6164-4402-8430-58891cbad6bb.jpg)

![error-ssh](https://user-images.githubusercontent.com/11556124/207294174-ecbe8003-3821-4609-82ff-11b4f7e2fa42.png)

I´m not sure... but I think that for some reason the action is trying to connect using passphrase and it shouldn't because it's empty
Can you help me?

Thanks in advance and congrats for the ssh-deploy action

**Comment by mkalygin** [comment]
Please see https://github.com/easingthemes/ssh-deploy/issues/90#issuecomment-1354700260.
