### ISSUE TITLE
⚠️ [Rsync] error:  rsync exited with code 23

### ISSUE THREAD

**Issue by easyf12** [easingthemes/ssh-deploy#92]
<img width="614" alt="image" src="https://user-images.githubusercontent.com/61322612/208801108-093cd8e6-113d-4fef-955d-46f224a05fd8.png">

<img width="834" alt="image" src="https://user-images.githubusercontent.com/61322612/208800873-bcecaf7d-7ce4-4701-ad47-00452e51ea7c.png">
I don't know why.
Can you help me?

**Comment by ain** [comment]
Reproduced, same error, also with `ed25519` key.

**Comment by easingthemes** [comment]
Check https://www.google.com/search?q=rsync+operation+not+permitted 
Test it manually. 
Depending on your system, you need to update `rsync` parameters

**Comment by ain** [comment]
`v4.0.4` tested to work, no issues.

**Comment by easyf12** [comment]
OK, I've solved the problem. Thanks.

**Comment by reddychenna** [comment]
@easyf12 how did u solve this issue

**Comment by mengliuliu** [comment]
> @easyf12 how did u solve this issue

how did u solve this issue
