### ISSUE TITLE
no file is changed when deployed

### ISSUE THREAD

**Issue by arslaneyah** [easingthemes/ssh-deploy#97]
when i push to my branch , the actions works fine but nothing is deployed 
![image](https://user-images.githubusercontent.com/35109201/210340035-d10d4e19-37bb-44ee-be42-844d3ab3b6c4.png)

**Comment by nocturnalpollinator** [comment]
I'm also facing issues in my deploy workflow. It finishes successfully but no files are changed or added on the server.

**Comment by nocturnalpollinator** [comment]
@arslaneyah I downgraded to [v3.1.0](https://github.com/easingthemes/ssh-deploy/releases/tag/v3.1.0) with `uses: easingthemes/ssh-deploy@v3.1.0` and it worked. It seem to have been a lot of activity the past 24 hours.

**Comment by josh-attwood** [comment]
Also having this issue, caused me a real headache today. 

@nocturnalpollinator, downgrading for the minute sorts it for the minute, thanks!

**Comment by easingthemes** [comment]
Hi, sorry for the issues.
v4 has a breaking change in default rsync arguments. 
Can you please share full log of the step?
- you can add 'ARGS' variable to old value. With this it will behave as v3.
- you can also use 'SCRIPT_BEFORE' and 'SCRIPT_AFTER' to investigate more, eg 'ls -l' remote folder.

**Comment by josh-attwood** [comment]
Hi @easingthemes,

Unfortunately this does not seem to be a problem with the default ARGS value as I already had this in (see .github code below).

`
name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@v3.1.0
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        ARGS: "-rltgoDzvO"
        SOURCE: ""
        REMOTE_HOST: ${{ secrets.FTP_HOST }}
        REMOTE_USER: ${{ secrets.FTP_USER}}
        TARGET: "*****"
`

The log is absolutely huge (which is not usually the case). I can email it over to you if that's helpful

**Comment by easingthemes** [comment]
With which version you have issues?
Can you please share step config?

**Comment by easingthemes** [comment]
Issue was with deafult source, is empty source is provided
Fixed in v4.0.1

**Comment by Syzuna** [comment]
now it just copies the whole runners file structure to my target folder, where it only copied the checked out repo files

**Comment by easingthemes** [comment]
Thanks for testing. I'm on it currently.

**Comment by easingthemes** [comment]
Fixed and new version released.
Latest 4.0.3.

**Comment by Syzuna** [comment]
Looks good now 👍🏼
